### ISSUE TITLE
ระบบสุ่มที่นั่ง (แบบมีเงื่อนไข)

### ISSUE THREAD

**Issue by TheNongice** [tuliptgr/randominclass#3]
ตัวเว็บยังคงมีบัคอยู่นะครับ กรณีที่ใส่เงื่อนไขผิดรูปแปปที่ตัวพี่ได้ทำไว้นะครับ บัคนี้ทำให้ Browser ที่ใช้เว็บของ**พี่ (หมายถึงเว็บที่พี่ทำนะครับ) เด้งหลุด หยุดการทำงาน**นะครับ

**Comment by tuliptgr** [comment]
ขอบคุณสำหรับ  feedback ครับ 🙏
ทางผู้จำทำจะนำคำแนะนำไปประปรุงต่อไปครับ😄
.
ขอสอบถามเพิ่มเติมนะครับ 
คุณพี่เจอเว็บไซต์นี้ผ่านช่องทางไหนครับ ?

**Comment by TheNongice** [comment]
ผมเจอเว็บนี้จากเพจ สภานักเรียน จภ.สตูล ครับ ^^
